import type {AppProps} from "next/app"
import Head from "next/head";

import {localesHome} from "@/constants/locales";
import Context from "@/context/store";
import "@/styles/main.scss"

export default function App({Component, pageProps}: AppProps) {
  return (
    <>
      <Head>
        <title>{localesHome.pageTitle}</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div className="page">
        <Context>
          <Component {...pageProps} />
        </Context>
      </div>
    </>)
}
